name: Backup Repository to S3

on:
  push:
    branches:
      - master

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y zip

    - name: Zip repository and store filename as env variable
      run: |
        timestamp=$(date +%Y%m%d%)
        zip -r prebidServerProdBackup-$timestamp.zip .
        echo "BACKUP_FILE=prebidServerProdBackup-$timestamp.zip" >> $GITHUB_ENV
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Upload to S3
      run: |
        aws s3 cp ${{ env.BACKUP_FILE }} s3://alkimi-db-backups/labsv2/prod/code_backups/prebidServerProdBackup
      env:
        BACKUP_FILE: ${{ env.BACKUP_FILE }}

    - name: Cleanup Zip Files
      run: |
        rm ${{ env.BACKUP_FILE }}
